In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import linear_model
from sklearn.preprocessing import OneHotEncoder


In [ ]:
# load data set
df=pd.read_csv('/content/drive/MyDrive/Python programming/Dataset_kaggle/kaggle_dataset/carprices.csv')
df.head(10)

Car Model  Mileage  Sell Price  Age
0          BMW X5    69000       18000    6
1          BMW X5    35000       34000    3
2          BMW X5    57000       26100    5
3          BMW X5    22500       40000    2
4          BMW X5    46000       31500    4
5            Audi    59000       29400    5
6            Audi    52000       32000    5
7            Audi    72000       19300    6
8            Audi    91000       12000    8
9  Mercedez Benz     67000       22000    6

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Car Model   16 non-null     object
 1   Mileage     16 non-null     int64 
 2   Sell Price  16 non-null     int64 
 3   Age         16 non-null     int64 
dtypes: int64(3), object(1)
memory usage: 640.0+ bytes


In [ ]:
#onhot encoding
dum_df=pd.get_dummies(df['Car Model'])
merg=df.join(dum_df) # you can also concate; pd.concat([df,dum_df], axis='columns')
merg

Car Model  Mileage  Sell Price  ...  BMW X5  Mercedez Benz   Toyota
0           BMW X5    69000       18000  ...       1               0       0
1           BMW X5    35000       34000  ...       1               0       0
2           BMW X5    57000       26100  ...       1               0       0
3           BMW X5    22500       40000  ...       1               0       0
4           BMW X5    46000       31500  ...       1               0       0
5             Audi    59000       29400  ...       0               0       0
6             Audi    52000       32000  ...       0               0       0
7             Audi    72000       19300  ...       0               0       0
8             Audi    91000       12000  ...       0               0       0
9   Mercedez Benz     67000       22000  ...       0               1       0
10  Mercedez Benz     83000       20000  ...       0               1       0
11  Mercedez Benz     79000       21000  ...       0               1       0
12  Mercedez Benz     59000       33000  ...       0               1       0
13          Toyota    51000       42000  ...       0               0       1
14          Toyota    65000       32000  ...       0               0       1
15          Toyota    39000       55000  ...       0               0       1

[16 rows x 8 columns]

In [ ]:
# now car model column must be removed, we split it in 4 section
final= merg.drop(['Car Model'], axis='columns')
final
# now the end of data preprocessing work, now model creat

Mileage  Sell Price  Age  Audi  BMW X5  Mercedez Benz   Toyota
0     69000       18000    6     0       1               0       0
1     35000       34000    3     0       1               0       0
2     57000       26100    5     0       1               0       0
3     22500       40000    2     0       1               0       0
4     46000       31500    4     0       1               0       0
5     59000       29400    5     1       0               0       0
6     52000       32000    5     1       0               0       0
7     72000       19300    6     1       0               0       0
8     91000       12000    8     1       0               0       0
9     67000       22000    6     0       0               1       0
10    83000       20000    7     0       0               1       0
11    79000       21000    7     0       0               1       0
12    59000       33000    5     0       0               1       0
13    51000       42000    4     0       0               0       1
14    65000       32000    7     0       0               0       1
15    39000       55000    5     0       0               0       1

In [ ]:
y=df['Sell Price'] # y in label column
x=final.drop(['Sell Price'], axis='columns') # x is the feature column
x

Mileage  Age  Audi  BMW X5  Mercedez Benz   Toyota
0     69000    6     0       1               0       0
1     35000    3     0       1               0       0
2     57000    5     0       1               0       0
3     22500    2     0       1               0       0
4     46000    4     0       1               0       0
5     59000    5     1       0               0       0
6     52000    5     1       0               0       0
7     72000    6     1       0               0       0
8     91000    8     1       0               0       0
9     67000    6     0       0               1       0
10    83000    7     0       0               1       0
11    79000    7     0       0               1       0
12    59000    5     0       0               1       0
13    51000    4     0       0               0       1
14    65000    7     0       0               0       1
15    39000    5     0       0               0       1

In [ ]:
model=linear_model.LinearRegression()

In [ ]:
model.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
model.score(x,y) # model efficiency or accuracy

0.9461669991799323

In [ ]:
model.predict([[45000, 8, 1,0,0,0]])

array([39677.03033127])

In [ ]:
# logisstic regression
df=pd.read_csv('/content/drive/MyDrive/Python programming/Dataset_kaggle/kaggle_dataset/marital status.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   age     20 non-null     int64  
 1   status  19 non-null     float64
dtypes: float64(1), int64(1)
memory usage: 448.0 bytes


In [ ]:
df.isnull().sum()

age       0
status    1
dtype: int64

In [ ]:
handle= df['status'].median()
df.status= df.status.fillna(handle)
df


age  status
0    21     0.0
1    33     1.0
2    24     0.0
3    28     1.0
4    17     0.0
5    33     1.0
6    23     0.0
7    30     0.0
8    29     1.0
9    22     0.0
10   26     1.0
11   20     0.0
12   22     0.0
13   24     0.0
14   34     1.0
15   29     1.0
16   16     0.0
17   18     0.0
18   26     1.0
19   25     1.0

In [ ]:
df['status'].value_counts()

0.0    11
1.0     9
Name: status, dtype: int64

In [ ]:
x=df[['age']] # independent variable or feature always kept in  double  bracket [[]]
y=df['status']


In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y, test_size=0.30, random_state=1)
from sklearn.linear_model import LogisticRegression

In [ ]:
model=LogisticRegression()
model.fit(xtrain,ytrain)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
model.predict(xtest)


array([1., 0., 0., 0., 0., 1.])

In [ ]:
model.score(xtest, ytest) # this is for logistic regression output, now sigmoid function's output

0.8333333333333334

In [ ]:
model.predict_proba(xtest) # this is the output for logistic function means sigmoid function output
# this output depends on this sigmond result or this probability

array([[0.28697051, 0.71302949],
       [0.9902967 , 0.0097033 ],
       [0.80161052, 0.19838948],
       [0.50311753, 0.49688247],
       [0.71810555, 0.28189445],
       [0.02465085, 0.97534915]])